CREATE TABLE `whatsapp_campaign_contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaign_id` int NOT NULL,
	`phone` varchar(20) NOT NULL,
	`name` varchar(255),
	`variables` json,
	`status` enum('pending','sent','delivered','read','failed','blocked') NOT NULL DEFAULT 'pending',
	`sent_at` timestamp,
	`delivered_at` timestamp,
	`read_at` timestamp,
	`failed_at` timestamp,
	`error_message` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `whatsapp_campaign_contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `whatsapp_campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`template_id` int,
	`session_id` varchar(100) NOT NULL,
	`status` enum('draft','scheduled','running','paused','completed','cancelled','failed') NOT NULL DEFAULT 'draft',
	`scheduled_start` timestamp,
	`scheduled_end` timestamp,
	`allowed_hours_start` int DEFAULT 9,
	`allowed_hours_end` int DEFAULT 18,
	`max_messages_per_hour` int DEFAULT 40,
	`max_messages_per_day` int DEFAULT 300,
	`auto_pause_enabled` boolean DEFAULT true,
	`auto_pause_threshold` int DEFAULT 5,
	`total_contacts` int DEFAULT 0,
	`messages_sent` int DEFAULT 0,
	`messages_delivered` int DEFAULT 0,
	`messages_read` int DEFAULT 0,
	`messages_failed` int DEFAULT 0,
	`messages_blocked` int DEFAULT 0,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`started_at` timestamp,
	`completed_at` timestamp,
	`paused_at` timestamp,
	`pause_reason` text,
	CONSTRAINT `whatsapp_campaigns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `whatsapp_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`category` varchar(100),
	`content` text NOT NULL,
	`variables` json,
	`description` text,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`is_active` boolean NOT NULL DEFAULT true,
	CONSTRAINT `whatsapp_templates_id` PRIMARY KEY(`id`)
);
