DROP TABLE `whatsapp_blacklist`;--> statement-breakpoint
DROP TABLE `whatsapp_block_alerts`;--> statement-breakpoint
DROP TABLE `whatsapp_send_history`;--> statement-breakpoint
DROP TABLE `obsidian_backlinks`;--> statement-breakpoint
DROP TABLE `obsidian_backups`;--> statement-breakpoint
DROP TABLE `obsidian_fluxos`;--> statement-breakpoint
DROP TABLE `obsidian_fluxos_log`;--> statement-breakpoint
DROP TABLE `obsidian_notas`;--> statement-breakpoint
DROP TABLE `obsidian_notas_historico`;--> statement-breakpoint
DROP TABLE `obsidian_notas_tags`;--> statement-breakpoint
DROP TABLE `obsidian_search_index`;--> statement-breakpoint
DROP TABLE `obsidian_sync_configs`;--> statement-breakpoint
DROP TABLE `obsidian_tags`;--> statement-breakpoint
DROP TABLE `obsidian_vaults`;--> statement-breakpoint
DROP TABLE `desktop_agents`;--> statement-breakpoint
DROP TABLE `desktop_commands`;--> statement-breakpoint
DROP TABLE `desktop_logs`;--> statement-breakpoint
DROP TABLE `desktop_screenshots`;--> statement-breakpoint
DROP TABLE `webhooks_config`;--> statement-breakpoint
DROP TABLE `webhooks_logs`;--> statement-breakpoint
DROP TABLE `ai_clients`;--> statement-breakpoint
DROP TABLE `ai_policies`;--> statement-breakpoint
DROP TABLE `ai_sessions`;--> statement-breakpoint
DROP TABLE `ai_trust_score_history`;--> statement-breakpoint
DROP TABLE `ai_violations`;--> statement-breakpoint
DROP TABLE `telemetry_anomalies`;--> statement-breakpoint
DROP TABLE `telemetry_events`;--> statement-breakpoint
DROP TABLE `telemetry_learnings`;--> statement-breakpoint
DROP TABLE `telemetry_metrics`;--> statement-breakpoint
DROP TABLE `telemetry_predictions`;--> statement-breakpoint
DROP TABLE `whatsapp_campaign_contacts`;--> statement-breakpoint
DROP TABLE `whatsapp_campaigns`;--> statement-breakpoint
DROP TABLE `whatsapp_templates`;--> statement-breakpoint
DROP TABLE `desktop_notifications`;--> statement-breakpoint
DROP TABLE `desktop_scheduled_commands`;--> statement-breakpoint
DROP TABLE `alert_configs`;--> statement-breakpoint
DROP TABLE `alert_history`;--> statement-breakpoint
DROP TABLE `alert_templates`;--> statement-breakpoint
DROP TABLE `ml_predictions`;